"""Small real wheels and hash locks for offline installation, integrity and declaration cases."""

import base64
import csv
import hashlib
import io
from collections.abc import Mapping
from pathlib import Path
from zipfile import ZipFile

from support.examples import EXAMPLES

ROUTER_DECLARATION = (EXAMPLES / "router.component.json").read_text(encoding="utf-8")


def component_files(module: str, declaration: str | None = ROUTER_DECLARATION) -> dict[str, str]:
    """A component package: `__main__.py` and, unless `None`, the shipped `component.json`."""
    files = {f"{module}/__init__.py": "", f"{module}/__main__.py": "raise SystemExit(3)\n"}
    if declaration is not None:
        files[f"{module}/component.json"] = declaration
    return files


def wheel(
    directory: Path,
    name: str,
    version: str,
    files: Mapping[str, str],
    requires: tuple[str, ...] = (),
) -> Path:
    """A pure-Python wheel with a valid `RECORD`; `files` maps archive paths to contents."""
    info = f"{name.replace('-', '_')}-{version}.dist-info"
    metadata = f"Metadata-Version: 2.3\nName: {name}\nVersion: {version}\n"
    metadata += "".join(f"Requires-Dist: {item}\n" for item in requires)
    contents = {path: text.encode() for path, text in files.items()}
    contents[f"{info}/METADATA"] = metadata.encode()
    contents[f"{info}/WHEEL"] = b"Wheel-Version: 1.0\nRoot-Is-Purelib: true\nTag: py3-none-any\n"
    record = io.StringIO()
    writer = csv.writer(record, lineterminator="\n")
    for path, content in contents.items():
        checksum = base64.urlsafe_b64encode(hashlib.sha256(content).digest()).decode().rstrip("=")
        writer.writerow((path, f"sha256={checksum}", len(content)))
    writer.writerow((f"{info}/RECORD", "", ""))
    contents[f"{info}/RECORD"] = record.getvalue().encode()
    target = directory / f"{name.replace('-', '_')}-{version}-py3-none-any.whl"
    with ZipFile(target, "x") as archive:
        for path, content in contents.items():
            archive.writestr(path, content)
    return target


def lockfile(directory: Path, wheels: tuple[Path, ...]) -> Path:
    """A lock in the multi-line form `uv pip compile --generate-hashes` writes."""
    lines = ["# This file was autogenerated by uv.\n"]
    for path in wheels:
        name, version, *_ = path.name.split("-")
        checksum = hashlib.sha256(path.read_bytes()).hexdigest()
        lines.append(f"{name}=={version} \\\n    --hash=sha256:{checksum}\n")
    lock = directory / "requirements.txt"
    lock.write_text("".join(lines))
    return lock
