"""Read-only operator capabilities keep HTTP independent of database implementations."""

from typing import Protocol

from ._operator_records import CommandReceipt, CommandResult


class OperatorSessions(Protocol):
    def create_session(self, command_id: str, name: str) -> CommandResult: ...
    def command(self, command_id: str) -> CommandReceipt | None: ...


class OperatorQueries(Protocol):
    def workspace(self, cursor: str | None) -> str: ...
    def run(self, run_id: str) -> str | None: ...
    def result(self, run_id: str) -> str | None: ...
    def events(self, run_id: str, cursor: str | None) -> str | None: ...
    def call(self, run_id: str, call_id: str, cursor: str | None) -> str | None: ...
    def payload(self, run_id: str, payload_id: str) -> str | None: ...
    def activation(self, run_id: str, activation_id: str, cursor: str | None) -> str | None: ...
    def definition(self, run_id: str) -> str | None: ...
    def execution(self, run_id: str, cursor: str | None) -> str | None: ...
    def session_runs(self, session_id: str, cursor: str | None) -> str | None: ...


class InvalidCursor(ValueError):
    """An opaque paging cursor is invalid or belongs to another query."""
