"""Run evidence and money share one transaction before any external dispatch."""

from contextlib import AbstractContextManager
from typing import Protocol

from slow_thinker_ii.access import InvocationEnd

from ._ledger import LedgerTransaction
from ._receipts import CallReceipt, ReceiptOutcome, SavedReceipt
from ._run_records import PreparedCall, RunEvent, RunRecord, RunState, StoredCall


class RecordingError(RuntimeError):
    """Recording failed; new work authority must close before another dispatch."""


class RunTransaction(LedgerTransaction, Protocol):
    def create_run(self, record: RunRecord) -> None: ...
    def run(self, run_id: str) -> RunRecord: ...
    def start(self, run_id: str) -> None: ...
    def reserve_charge(self, call: PreparedCall, run: RunRecord) -> None: ...
    def record_call(self, call: PreparedCall) -> None: ...
    def call(self, call_id: str) -> StoredCall: ...
    def cancel_call(self, call_id: str) -> None: ...
    def authorize(self, call_id: str) -> None: ...
    def stop(self, run_id: str, reason: str, state: RunState = "stopping") -> None: ...
    def event(self, run_id: str, event: str, call_id: str | None, payload: str) -> None: ...
    def events(self, run_id: str) -> tuple[RunEvent, ...]: ...
    def receipt(self, receipt_id: str) -> SavedReceipt | None: ...
    def check_receipt(self, receipt: CallReceipt) -> ReceiptOutcome | None: ...
    def receive(
        self,
        receipt: CallReceipt,
        gate: InvocationEnd,
        now: float,
        runtime_id: str,
    ) -> ReceiptOutcome: ...
    def unfinished(self) -> tuple[RunRecord, ...]: ...
    def finish_run(
        self, run_id: str, runtime_id: str, now: float, output_json: str | None, *, executing: bool
    ) -> RunRecord: ...


class RunStore(Protocol):
    def begin(self) -> AbstractContextManager[RunTransaction]: ...
